export const switzerHotelSuggestions = [
  "Alpine Retreat Hotel",
  "Lake Geneva Resort",
  "Swiss Alps Resort",
  "Lake Geneva Hotel",
  "Zurich City Stay",
  "Interlaken Adventure Lodge",
  "Lucerne Lake Hotel",
  "Bern Boutique Hotel",
  "St. Moritz Ski Resort",
  "Grindelwald Lodge",
  "Chateau de Gruyères Hotel",
  "Zermatt Mountain View Resort",
  "Montreux Riviera Hotel",
  "Interlaken Park Lodge",
  "Lucerne City Hotel",
  "St. Gallen Boutique Hotel",
  "Basel Art District Hotel",
  "Zurich",
  "Geneva",
  "Basel",
  "Lausanne",
  "Bern",
  "Lucerne",
  "St. Gallen",
  "Lugano",
  "Biel/Bienne",
  "Thun",
  "Winterthur",
  "Fribourg",
  "Schaffhausen",
  "Neuchâtel",
  "Sion",
  "Chur",
  "Zug",
  "Yverdon-les-Bains",
  "Montreux",
  "Uster",
  "Vernier",
  "Interlaken",
  "St. Moritz",
  "Grindelwald",
  "Zermatt",
  "Montreux",
];
